export const KEYWORD_MAP = {
    // મૂળભૂત કીવર્ડ્સ (Basic Keywords)
    'ઈમ્પોર્ટ': 'import',
    'ડેફ': 'def',
    'ક્લાસ': 'class',
    'ફોર': 'for',
    'વ્હાઈલ': 'while',
    'જો': 'if',
    'નહીં તો': 'else',
    'અથવા જો': 'elif',
    'પરત આપો': 'return',
    'છાપો': 'print',
    'સાચું': 'True',
    'ખોટું': 'False',
    'કંઈ નહીં': 'None',
    'અને': 'and',
    'અથવા': 'or',
    'નહીં': 'not',
    'ઇન': 'in',
    'છે': 'is',
    'સાથે': 'with',
    'આસ': 'as',
    'માંથી': 'from',
    'પ્રયત્ન કરો': 'try',
    'સિવાય': 'except',
    'અંતે': 'finally',
    'ઊઠાવો': 'raise',
    'લેમ્બડા': 'lambda',
    'વૈશ્વિક': 'global',
    'બિન સ્થાનિક': 'nonlocal',
    'ખાતરી કરો': 'assert',
    'બ્રેક': 'break',
    'ચાલુ રાખો': 'continue',
    'પાસ': 'pass',
    'ડિલીટ કરો': 'del',
    'પ્રદાન કરો': 'yield',
    'અસિન્ક': 'async',
    'રાહ જુઓ': 'await',
    'મેચ': 'match',
    'કેસ': 'case',
};

export const BUILTIN_MAP = {
    // બિલ્ટ-ઇન ફંક્શન્સ (Built-in Functions)
    'લેન': 'len',
    'રેંજ': 'range',
    'ટાઇપ': 'type',
    'સ્ટ્ર': 'str',
    'ઇન્ટ': 'int',
    'ફ્લોટ': 'float',
    'લિસ્ટ': 'list',
    'ડિક્ટ': 'dict',
    'સેટ': 'set',
    'ટ્યુપલ': 'tuple',
    'ઓપન': 'open',
    'મિન': 'min',
    'મેક્સ': 'max',
    'સમ': 'sum',
    'સોર્ટેડ': 'sorted',
    'રેવર્સેડ': 'reversed',
    'એની': 'any',
    'ઓલ': 'all',
    'મેપ': 'map',
    'ફિલ્ટર': 'filter',
    'ઝીપ': 'zip',
    'એન્યુમરેટ': 'enumerate',
    'ઈનપુટ': 'input',
    'ઈવલ': 'eval',
    'એક્ઝેક': 'exec',
    'કોમ્પાઇલ': 'compile',
    'હેશ': 'hash',
    'આઈડી': 'id',
    'વાર્સ': 'vars',
    'ડાઇર': 'dir',
    'હેલ્પ': 'help',
    'રાઉન્ડ': 'round',
    'એબ્સ': 'abs',
    'પાવર': 'pow',
    'ડિવમોડ': 'divmod',
    'બિન': 'bin',
    'ઓક્ટ': 'oct',
    'હેક્સ': 'hex',
    'ઓર્ડ': 'ord',
    'ક્રોમ': 'chr',
    'બૂલ': 'bool',
    'બાઇટ્સ': 'bytes',
    'બાઇટઆરે': 'bytearray',
    'કોમ્પ્લેક્સ': 'complex',
    'ફ્રોઝનસેટ': 'frozenset',
    'મેમરીવ્યુ': 'memoryview',
    'ઓબ્જેક્ટ': 'object',
    'પ્રોપર્ટી': 'property',
    'સ્લાઇસ': 'slice',
    'સુપર': 'super',
    'સ્ટેટિકમેથડ': 'staticmethod',
    'ક્લાસમેથડ': 'classmethod',
};

export const MODULE_MAP = {
    // મોડ્યુલ્સ (Modules)
    'ગણિત': 'math',
    'રેન્ડમ': 'random',
    'અવિકલ': 'time',
    'સમય': 'time',
    'તારીખ_સમય': 'datetime',
    'ઓપરેટિંગ_સિસ્ટમ': 'os',
    'સિસ્ટમ': 'sys',
    'શબ્દમાળા': 'string',
    'કાચબો': 'turtle',
};

export const TURTLE_MAP = {
    'કાચબો.આગળ': 'turtle.forward',
    'કાચબો.પાછળ': 'turtle.backward',
    'કાચબો.ડાબે': 'turtle.left',
    'કાચબો.જમણે': 'turtle.right',
    'કાચબો.ઉપર': 'turtle.up',
    'કાચબો.નીચે': 'turtle.down',
    'કાચબો.રંગ': 'turtle.color',
    'કાચબો.શરૂ': 'turtle.begin_fill',
    'કાચબો.બંધ': 'turtle.end_fill',
    'કાચબો.ગતિ': 'turtle.speed',
    'કાચબો.છાપો': 'turtle.write',
    'કાચબો.વર્તુળ': 'turtle.circle',
    'કાચબો.આકાર': 'turtle.shape',
    'કાચબો.ગોલ': 'turtle.done',
    'કાચબો.ગયા': 'turtle.goto',
};

export const MATH_MAP = {
    'ગણિત.વર્ગમૂળ': 'math.sqrt',
    'ગણિત.પાઈ': 'math.pi',
    'ગણિત.સીલ': 'math.ceil',
    'ગણિત.ફ્લોર': 'math.floor',
    'ગણિત.ફેક્ટોરિયલ': 'math.factorial',
    'ગણિત.સાઈન': 'math.sin',
    'ગણિત.કોસ': 'math.cos',
    'ગણિત.ટેન': 'math.tan',
    'ગણિત.ઘાત': 'math.pow',
};
